### ISSUE TITLE
find better chart release process

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon-charts#102] opened 2020-10-01 14:39 UTC
So I think we need to find a better chart release process than we have today.

As it is right now with `check-version-increment` set to the default of true (see: https://github.com/uselagoon/lagoon-charts/commit/2331cbd3af805e4acebca0c693bc4dc93378c800) each PR needs to bump the version to the next version, I think this is not really nice because:
1. it needs every contributor to know this, if we really want this we should have a pre-commit hook or something that checks this as the DX is now quite bad: you push a change and your PR is gonna fail immediately every actually linting your code (the linter does not even lint if the version bump is wrong)
2. if you have 3 PRs that you want to test on each other, you need to merge the first, bump the version on the two others, merge the second, bump the version on the last, merge. This seems like a way to complex system and will people cause to send hughe PRs instead of smaller digestible ones.
3. it's not how we have worked so far in lagoon, currently contributors just send us PRs and the maintainers then decide in which version something goes in. With the current active system in lagoon-charts it's almost he contributors saying in which version it goes in, if the maintainers want to add it to another version they have to actually change code

because of all of this we added `check-version-increment: false` as this then just lints the code and does not enforce a version bump.
The version bump itself is then enforced inside the release workflow:
- initially we added another linting step to the release workflow, but had to realize that this is not meant to be used that way (as the `helm/chart-testing-action` action first checks if there are changes and only then starts to lint (see https://github.com/helm/chart-testing-action/blob/master/ct.sh#L39-L44), while this works in a PR during a branch build there are no changes (`ct list-changed` returns nothing) and so the linter actually will never do anything, so we removed it again.
- then though we realized that `helm/chart-releaser-action` actually also fails if we try to release a version that already exists and will not overwrite any releases. While this is also not a great DX  (would be much better to actually tell why exactly it failed) it's better than nothing
- we then also tried to change the release process all together from release on each `main` branch push to a release on creating a new tag. Unfortunately this also doesn't work as the `helm/chart-releaser-action` is meant to run on a branch, it checks first if we have changes that are not tagged yet and only then will pack the charts and create a new tag by itself. As we though just created a tag manually it will decide to not do anything 🤦 and never release anything.

so my plan was to have this:

1. PRs are linted, not version checked
2. lagoon-charts maintainers are merging in PRs they want to release (release build will fail as the version bump did not happen yet)
3. when the maintainers feel they are ready to release a new version, they commit directly a version bump into the main branch and the release charts

Overall I think that process could work, the only sad thing are the failed release builds on step 2

**Comment by Schnitzel** [comment] 2020-10-01 14:41
possible idea for solution of step2:
we do a manual workflow run in github actions to release: https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/manually-running-a-workflow

**Comment by smlx** [comment] 2020-10-02 03:06
> So I think we need to find a better chart release process than we have today.

Hey @Schnitzel, thanks for the feedback.

The main reasons that I designed the CI system this way are:

1. It enforces that each PR is release-ready before merge.
2. `main` branch is _always_ releasable, and the code in `main` always reflects the latest available chart versions.
3. The CI/CD and release process is as automated as possible.
4. It aligns with the opinionated way that the helm chart-testing and release tooling works.

I agree that the system is quite rigid, but IMHO that results in better release engineering and more rapid releases.

> As it is right now with `check-version-increment` set to the default of true (see: [2331cbd](https://github.com/uselagoon/lagoon-charts/commit/2331cbd3af805e4acebca0c693bc4dc93378c800)) each PR needs to bump the version to the next version, I think this is not really nice because:
> 
>     1. it needs every contributor to know this, if we really want this we should have a pre-commit hook or something that checks this as the DX is now quite bad: you push a change and your PR is gonna fail immediately every actually linting your code (the linter does not even lint if the version bump is wrong)

Yes that is true, I should add a note about this requirement to the PR template.
However bumping the version is IMHO a small imposition and, if you forget to bump the version, the problem is quickly obvious from the CI log.

The version bump requirement also has these advantages:

* since chart version numbering uses [Semantic Versioning](https://semver.org), it forces contributors and reviewers to consider the scope of the changes at the point of merge: are these changes just a bugfix, a backwards-compatible feature addition, or a breaking change? this is important because the helm ecosystem relies heavily on the semantics of SemVer, and making a mistake here will impact anyone using the chart.
* it means that the _only_ thing you have to do is bump the version and `git push` - test and release is fully automated.
* you can `helm install` your change immediately after it is accepted into `main`.

>     2. if you have 3 PRs that you want to test on each other, you need to merge the first, bump the version on the two others, merge the second, bump the version on the last, merge. This seems like a way to complex system and will people cause to send hughe PRs instead of smaller digestible ones.

Isn't the process that you describe, of reviewing and merging each PR separately, what we _want_ to happen?
If the 3 PRs are so closely coupled that they need to be reviewed/merged together, then doesn't that mean that they should instead be a single PR (even if it is large)?

I would have thought that the current CI process would cause people to send _smaller_ PRs more often instead of larger ones, since the barrier to getting a change into a release quickly is so low.

>     3. it's not how we have worked so far in lagoon, currently contributors just send us PRs and the maintainers then decide in which version something goes in. With the current active system in lagoon-charts it's almost he contributors saying in which version it goes in, if the maintainers want to add it to another version they have to actually change code

Yes, this is different to Lagoon. But having `main` constantly releasable (and, in fact, released) is pretty standard continuous delivery workflow.
In this system the version number itself doesn't actually matter because it is dictated by the specifics of the change itself (due to Semantic Versioning).

> because of all of this we added `check-version-increment: false` as this then just lints the code and does not enforce a version bump.
> The version bump itself is then enforced inside the release workflow:
> 
>     * initially we added another linting step to the release workflow, but had to realize that this is not meant to be used that way (as the `helm/chart-testing-action` action first checks if there are changes and only then starts to lint (see https://github.com/helm/chart-testing-action/blob/master/ct.sh#L39-L44), while this works in a PR during a branch build there are no changes (`ct list-changed` returns nothing) and so the linter actually will never do anything, so we removed it again.
> 
>     * then though we realized that `helm/chart-releaser-action` actually also fails if we try to release a version that already exists and will not overwrite any releases. While this is also not a great DX  (would be much better to actually tell why exactly it failed) it's better than nothing
> 
>     * we then also tried to change the release process all together from release on each `main` branch push to a release on creating a new tag. Unfortunately this also doesn't work as the `helm/chart-releaser-action` is meant to run on a branch, it checks first if we have changes that are not tagged yet and only then will pack the charts and create a new tag by itself. As we though just created a tag manually it will decide to not do anything facepalm and never release anything.
> 
> 
> so my plan was to have this:
> 
>     1. PRs are linted, not version checked
> 
>     2. lagoon-charts maintainers are merging in PRs they want to release (release build will fail as the version bump did not happen yet)
> 
>     3. when the maintainers feel they are ready to release a new version, they commit directly a version bump into the main branch and the release charts
> 
> 
> Overall I think that process could work, the only sad thing are the failed release builds on step 2

Could you elaborate on the advantages of this workflow?

From what I can see it has these disadvantages:

* changes take a long time to actually make it into a release
* adds manual work of "cutting a release" instead of just constantly having `main` released automatically
* maintainers have to inspect a (possibly large) diff since the last tagged release to figure out how to correctly bump the version according to Semantic Versioning rules.
* maintainers have to commit untested changes directly to `main`

And these advantages:

* no need to version bump in PRs

**Comment by tobybellwood** [comment] 2020-10-02 03:11
Even making sure that people enter a feasible chart number - we can always comment/suggest/commit a different one if needed - but only if they include it in the PR.

**Comment by smlx** [comment] 2020-10-05 08:40
I still think the current fully-automated process is better, but this is another way the manual release process could work:

  1. PRs into `main` are linted and installed, but not version checked
  2. create a new branch called `release`, and point the `chart-releaser` action at the `release` branch
  3. when a maintainer wants a new release they merge `main` into `release`, and bump any chart versions that need it

  This has all the disadvantages listed in my previous comment, but at least the release action doesn't run/fail on every merge.

**Comment by smlx** [comment] 2021-07-12 09:30
Now that we have used the current release process for the charts for a while, how do you feel about it @Schnitzel / @tobybellwood? Are there problems that still need to be solved? Or should I close this issue?

**Comment by tobybellwood** [comment] 2021-07-12 09:39
I'm used to it now.  The only persistent grumble is keeping the chart versions suitably incremented, but I think we're ok to close this now.

**Comment by smlx** [comment] 2021-07-14 07:53
Closing as per above.

**Closed by smlx** 2021-07-14 07:53 UTC
Labels: all charts
